### ISSUE TITLE
Allow more than 5 GPU's

### ISSUE THREAD

**Issue by MaynardMiner** [Belgarion/cuballoon#2]
--cuda_devices seems to allow only 0-3 GPU's.

Please allow it to work up to 20, if possible.

**Comment by Belgarion** [comment]
--cuda_devices should be able to handle 32 devices already (although there might still be parts of the program that can't handle more than 20 devices).

Please provide exact command you used for starting cuballoon and the start of the output (all output from beginning until first submitted share).

**Comment by MaynardMiner** [comment]
My mining script (which I added your miner) can divide up miner to mining groups, so I am running more than one instance of your miner dividing up GPU's-

--cuda_devices $Devices -t 0 -a $_ -o stratum+tcp://$($Pools.(Get-Algo($_)).Host):$($Pools.(Get-Algo($_)).Port) -b 0.0.0.0:4069 -u $($Pools.(Get-Algo($_)).User1) -p $($Pools.(Get-Algo($_)).Pass1) $($Commands.$_)

This translates to --cuda_devices (Devices) -t 0 -a (balloon) -o stratum+tcp:/(Pool Address):(Pool Port) -b (API Bind) -u (Wallet) -p (Password) (additional commands, which are threads and blocks)

for my testing, first instance --cuda_devices was 0,1,2,3,4  then second instance --cuda_devices 5,6,7,8 then third instance --cuda_devices 9,10,11,12

Miner would open up three instances, but all three were 0,1,2,3,4  devices. All three miners crash.

Could it be the -t 0?

Also is there a way to run the miner with just cpu only? I tried without --cude_devices, and it wanted to use gpu's.

**Comment by MaynardMiner** [comment]
Also I did my testing on linux version, if that matters, compiles cuda 9.2 nvidia 396 drivers.

**Comment by cryptozeny** [comment]
build is no problem on ubuntu 16.04 great! cuda9.2 nvidia396

**Comment by MaynardMiner** [comment]
That is what I used. I will look at it again, and try to hold screen to see what it is. I'm new to using this miner. But I can't get it to work without cuda, and just use CPU, though.

Side note- is there support for 1050ti? 

On my smaller test windows miner 1050ti seems to always close, no matter how low I set the the threads or blocks.

**Comment by cryptozeny** [comment]
if you use only cpu for mining, use the cpuminer-balloon. this is gpuminer 😅

**Comment by MaynardMiner** [comment]
I know you can use gpuminer. I was asking if it had an option, so I didn't have to add another miner to my program.

**Comment by MaynardMiner** [comment]
CUDA error at balloon/ballon-cuda.cu:163 code=11(cudaErrorInvalidValue)

I am actually getting this error. It flashes for a second, I held window open to see it. I was assuming it was a device issue because I didn't realize that it denotes GPUs starting at 0 internally. I thought it was trying to mine on all the same GPUs.

I think it's a memory allocation error. Which in my experience means I am botching compiling...Maybe the purge of the old toolkit and update of the new didn't work out right. Either way it's likely an issue on my end likely. I am closing.
